---
title: "About"
format:
  html:
    toc: false
---

I am a Ph.D. candidate in [Survey and Data Science](https://surveydatascience.isr.umich.edu) (formerly Survey Methodology) at the University of Michigan and a maintainer of [ASReview LAB](https://asreview.nl), an open-source AI-based research software.

## Education

{{< iconify fa6-solid graduation-cap >}} **University of Michigan** \| Ann Arbor, MI

Ph.D. in Survey and Data Science \| August 2022 -- Present


{{< iconify fa6-solid graduation-cap >}} **Utrecht University** \| The Netherlands

M.Sc. in Methodology and Statistics \| September 2019 -- May 2021

{{< iconify fa6-solid graduation-cap >}} **University of Macau**

M.S.Sc. in Criminology and Criminal Justice \| August 2017 -- June 2019

{{< iconify fa6-solid certificate >}} **Linköping University** \| Sweden

Exchange, Computational Social Science \| August 2018 -- January 2019


## Selected Awards

Charles Cannell Fund in Survey Methodology, University of Michigan \| 2024

Student Fellowship, Midwest Association for Public Opinion Research (MAPOR) \| 2023

Outgoing Exchange Scholarship, University of Macau \| 2018
